display_name: X Minecraft Server Launcher
publisher_display_name: Zachary_QwQ
identity_name: org.mcfso.lrix
msix_version: 1.0.0.0
logo_path: windows\runner\resources\app_icon.ico
capabilities: internetClient
architecture: x64
