display_name: X Minecraft Server Launcher
summary: A Flutter application for managing Minecraft servers.
group: Applications/System
vendor: MCFSO
license: MIT
url: https://github.com/MCFSO/xmcserverlancher
icon: macos/Runner/Assets.xcassets/AppIcon.appiconset/app_icon_512.png
generic_name: Minecraft Server Manager
keywords:
  - minecraft
  - server
  - launcher
categories:
  - Utility
